In [ ]:
import numpy as np
def Euclidian_Dist(x,y):
  return np.linalg.norm(x-y) #write your code here

def Dist_mat(X):
  #write your code here
  dist_mat=np.zeros((len(X),len(X)))
  for i in range(len(X)):
    for j in range(len(X)):
      dist_mat[i,j]=round(Euclidian_Dist(X[i],X[j]),2) if i!=j else np.inf
  return dist_mat

def combine(X,D):
  #write your code here
  a,b = np.unravel_index(np.argmin(D, axis=None), D.shape)
  a,b=(b,a) if b<a else (a,b)
  print("Vector of X to be combined : " + str(a+1) + "," + str(b+1))
  X[a]=(X[a]+X[b])/2
  newX=np.delete(X,b,0)
  D[a,:]=(D[a,:]+D[b,:])/2
  D[:,a]=(D[:,a]+D[:,b])/2
  D=np.delete(D,b,0)
  D=np.delete(D,b,1)
  return newX,a,b,D

X=np.array([[1,1],[2,1],[5,4],[6,5],[6.5,6]])
print(X.T)
#write your code here
n=1 #number_of_cluster
newX=X
label=[[i] for i in range(len(X))]
D=Dist_mat(newX)
while newX.shape[0]>n:
  print(D)
  newX,a,b,D=combine(newX,D)
  label[a]+=label[b]
  label.pop(b)
  print()
  print(newX.T)
print(label)
## velidate from inbuilt Dendogram

import plotly.figure_factory as ff

lab=np.linspace(1,X.shape[0],X.shape[0])
fig = ff.create_dendrogram(X, labels=lab)
fig.update_layout(width=800, height=300)
fig.show()

[[1.  2.  5.  6.  6.5]
 [1.  1.  4.  5.  6. ]]
[[ inf 1.   5.   6.4  7.43]
 [1.    inf 4.24 5.66 6.73]
 [5.   4.24  inf 1.41 2.5 ]
 [6.4  5.66 1.41  inf 1.12]
 [7.43 6.73 2.5  1.12  inf]]
Vector of X to be combined : 1,2

[[1.5 5.  6.  6.5]
 [1.  4.  5.  6. ]]
[[ inf 4.62 6.03 7.08]
 [4.62  inf 1.41 2.5 ]
 [6.03 1.41  inf 1.12]
 [7.08 2.5  1.12  inf]]
Vector of X to be combined : 3,4

[[1.5  5.   6.25]
 [1.   4.   5.5 ]]
[[  inf 4.62  6.555]
 [4.62    inf 1.955]
 [6.555 1.955   inf]]
Vector of X to be combined : 2,3

[[1.5   5.625]
 [1.    4.75 ]]
[[   inf 5.5875]
 [5.5875    inf]]
Vector of X to be combined : 1,2

[[3.5625]
 [2.875 ]]
[[0, 1, 2, 3, 4]]


In [ ]:
X = np.array([[5,3],
    [10,15],
    [15,12],
    [24,10],
    [30,30],
    [85,70],
    [71,80],
    [60,78],
    [70,55],
    [80,91],])
print(X.T)
#write your code here
n=3 #number_of_cluster
newX=X
label=[[i] for i in range(len(X))]
D=Dist_mat(newX)
while newX.shape[0]>n:
  print(D)
  newX,a,b,D=combine(newX,D)
  label[a]+=label[b]
  label.pop(b)
  print()
  print(newX.T)
print(label)
## velidate from inbuilt Dendogram

import plotly.figure_factory as ff

lab=np.linspace(1,X.shape[0],X.shape[0])
fig = ff.create_dendrogram(X, labels=lab)
fig.update_layout(width=800, height=300)
fig.show()

[[ 5 10 15 24 30 85 71 60 70 80]
 [ 3 15 12 10 30 70 80 78 55 91]]
[[   inf  13.    13.45  20.25  36.8  104.35 101.41  93.01  83.24 115.62]
 [ 13.      inf   5.83  14.87  25.    93.01  89.14  80.43  72.11 103.32]
 [ 13.45   5.83    inf   9.22  23.43  90.91  88.09  79.88  69.81 102.3 ]
 [ 20.25  14.87   9.22    inf  20.88  85.56  84.31  76.94  64.35  98.47]
 [ 36.8   25.    23.43  20.88    inf  68.01  64.66  56.6   47.17  78.87]
 [104.35  93.01  90.91  85.56  68.01    inf  17.2   26.25  21.21  21.59]
 [101.41  89.14  88.09  84.31  64.66  17.2     inf  11.18  25.02  14.21]
 [ 93.01  80.43  79.88  76.94  56.6   26.25  11.18    inf  25.08  23.85]
 [ 83.24  72.11  69.81  64.35  47.17  21.21  25.02  25.08    inf  37.36]
 [115.62 103.32 102.3   98.47  78.87  21.59  14.21  23.85  37.36    inf]]
Vector of X to be combined : 2,3

[[ 5 12 24 30 85 71 60 70 80]
 [ 3 13 10 30 70 80 78 55 91]]
[[    inf  13.225  20.25   36.8   104.35  101.41   93.01   83.24  115.62 ]
 [ 13.225     inf  12.045  24.21

In [ ]:
# Agglomerative Clustering

def agglo_clust(X,n):
  import numpy as np
  def Euclidian_Dist(x,y):
    return np.linalg.norm(x-y) #write your code here

  def Dist_mat(X):
    #write your code here
    dist_mat=np.zeros((len(X),len(X)))
    for i in range(len(X)):
      for j in range(len(X)):
        dist_mat[i,j]=round(Euclidian_Dist(X[i],X[j]),2) if i!=j else np.inf
    return dist_mat

  def combine(X,D):
    #write your code here
    a,b = np.unravel_index(np.argmin(D, axis=None), D.shape)
    a,b=(b,a) if b<a else (a,b)
    # print("Vector of X to be combined : " + str(a+1) + "," + str(b+1))
    X[a]=(X[a]+X[b])/2
    newX=np.delete(X,b,0)
    D[a,:]=(D[a,:]+D[b,:])/2
    D[:,a]=(D[:,a]+D[:,b])/2
    D=np.delete(D,b,0)
    D=np.delete(D,b,1)
    return newX,a,b,D

  #write your code here
  newX=X
  label=[[i] for i in range(len(X))]
  D=Dist_mat(newX)
  while newX.shape[0]>n:
    print(label)
    newX,a,b,D=combine(newX,D)
    label[a]+=label[b]
    label.pop(b)
    # print()
    # print(newX.T)
  
  l=[-1 for _ in range(len(X))]
  for i in range(len(label)):
    for j in label[i]:
      l[j]=i
  return l

In [ ]:
ll=agglo_clust(X,0)

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]]
[[0], [1, 2], [3], [4], [5], [6], [7], [8], [9]]
[[0], [1, 2, 3], [4], [5], [6], [7], [8], [9]]
[[0], [1, 2, 3], [4], [5], [6, 7], [8], [9]]
[[0, 1, 2, 3], [4], [5], [6, 7], [8], [9]]
[[0, 1, 2, 3], [4], [5], [6, 7, 9], [8]]
[[0, 1, 2, 3], [4], [5, 8], [6, 7, 9]]
[[0, 1, 2, 3], [4], [5, 8, 6, 7, 9]]
[[0, 1, 2, 3, 4], [5, 8, 6, 7, 9]]
[[0, 1, 2, 3, 4, 5, 8, 6, 7, 9]]
