In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np

# write your code here
import csv
with open('/content/drive/My Drive/Recommendation System Project/song_feature.csv') as file:
  csvreader=csv.reader(file)
  # fields=next(csvreader)
  x=[]
  for row in csvreader:
    x.append(list(map(float,row)))

song=np.array(x)
print(song.shape)
print(song)

(9938, 5)
[[-0.26223832 -0.57915429  0.1681672  -0.02099148  0.4289463 ]
 [ 1.18749093  0.8382921   6.7238765  -0.9119011   1.11066879]
 [ 1.49687383 -1.06554503  0.3335669  -1.3569191  -0.53465016]
 ...
 [-0.4028443  -0.47656519  0.46963926  0.81699222  0.06095219]
 [ 0.13952206 -0.2022439  -0.10495276  0.42588791 -0.36766231]
 [-0.41901508  0.61610373 -0.37797701  0.31844266  0.84502606]]


In [ ]:
import numpy as np

# write your code here
import csv
with open('/content/drive/My Drive/Recommendation System Project/meta.csv') as file:
  csvreader=csv.reader(file)
  fields=next(csvreader)
  fields=next(csvreader)
  x=[]
  for row in csvreader:
    x.append(row[2:])

song_data=np.array(x)
print(song_data.shape)
print(song_data)

(9938, 5)
[['SOAKIMP12A8C130995' 'The Cove' 'Thicker Than Water' 'Jack Johnson' '0']
 ['SOBBMDR12A8C13253B' 'Entre Dos Aguas' 'Flamenco Para Niños'
  'Paco De Lucia' '1976']
 ['SOBXHDL12A81C204C0' 'Stronger' 'Graduation' 'Kanye West' '2007']
 ...
 ['SOGCHYZ12AF72A69EC' 'That Tree (feat. Kid Cudi)'
  'That Tree Featuring Kid Cudi' 'Snoop Dogg featuring Kid Cudi' '2010']
 ['SOOAAQL12B0B80B6D1' 'Borders' 'Dreams' 'The Whitest Boy Alive' '2006']
 ['SOSSZPW12A8C13843D' 'Figures' 'Dreams' 'The Whitest Boy Alive' '2006']]


In [ ]:
# print(ind)
# print(arr[ind])
# print(max(arr))

In [ ]:
def recommend_me(n):
  arr=[]
  for i in range(len(song)):
    arr.append(np.linalg.norm(song[n]-song[i]))
  arr=np.array(arr)
  ind = arr.argsort()[:5]
  print("Recommended songs for "+song_data[n][1]+" by "+song_data[n][3] + " are :")
  print()
  for i in ind[1:]:
    print(song_data[i][1]+" by "+song_data[i][3])
  print("-------------------------------------------------------")

In [ ]:
recommend_me(12)  #345 #12 #119

Recommended songs for Love Shack by The B-52's are :

Come On Over (All I Want Is You) by Christina Aguilera
Reign of Terror by Beneath the Massacre
I'm Goin' Away by Graham Coxon
What They Found by Octopus Project
-------------------------------------------------------


In [ ]:
recommend_me(660)

Recommended songs for Street Justice by MSTRKRFT are :

Consequence Of Sounds by Regina Spektor
Wet Blanket by Metric
sillyworld (Album Version) by Stone Sour
Polaris by Zero 7
-------------------------------------------------------


In [ ]:
recommend_me(429)

Recommended songs for Angel Echoes by Four Tet are :

When You Say You Love Me (Album Version) by Josh Groban
Damelo by Juanes
Mistadobalina by Del Tha Funkee Homosapien
We Will Become Silhouettes (Album) by Postal Service
-------------------------------------------------------
